[project]
name = "backend"
version = "0.1.0"
description = "A backend for website ingestion and embedding."
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "beautifulsoup4>=4.12.3",
    "cohere>=5.20.0",
    "qdrant-client>=1.16.1",
    "trafilatura>=2.0.0",
]
